/**
 * TACO Foodies Master Menu Data
 * Fully Audited Dataset - 68 Dishes with 100% Distinct & Unique Physical Local Food Images
 * Synchronized with uploaded menu cards, local images folder, and Supabase database.
 */
const DEFAULT_MENU_DATA = [
  // --- STARTERS & TACOS ---
  {
    id: "tf_1",
    name: "Peri Peri French Fries",
    category: "Starters",
    price: 39,
    originalPrice: 49,
    discount: "20% OFF",
    rating: 4.8,
    ratingCount: 110,
    image: "images/peri_peri_fries.jpg",
    description: "Crispy, golden-brown fries with a zesty, spicy kick from peri peri spices, offering a delightful combination of heat and savory flavor.",
    isVeg: true,
    spicyLevel: 2,
    isTrending: true,
    isTodayDeal: false,
    tag: "Bestseller"
  },
  {
    id: "tf_2",
    name: "Chicken Taco",
    category: "Starters",
    price: 149,
    originalPrice: 179,
    discount: "15% OFF",
    rating: 4.9,
    ratingCount: 145,
    image: "images/chicken_taco.jpg",
    description: "Chicken, lemon, olive oil, lemon juice, signature salsa in soft tortillas skillet cooked over medium heat.",
    isVeg: false,
    spicyLevel: 2,
    isTrending: true,
    isTodayDeal: true,
    tag: "Mexican Special"
  },
  {
    id: "tf_3",
    name: "Fish Taco",
    category: "Starters",
    price: 129,
    originalPrice: 159,
    discount: "18% OFF",
    rating: 4.7,
    ratingCount: 88,
    image: "images/fish_taco.jpg",
    description: "Mix butter, lime juice, chili powder, garlic powder, and salt in a small bowl. Pour mixture over golden fried fish.",
    isVeg: false,
    spicyLevel: 1,
    isTrending: false,
    isTodayDeal: false,
    tag: "Seafood Taco"
  },
  {
    id: "tf_4",
    name: "Mutton Tacos",
    category: "Starters",
    price: 185,
    originalPrice: 219,
    discount: "15% OFF",
    rating: 5.0,
    ratingCount: 160,
    image: "images/chicken_taco.jpg",
    description: "Lamb Tacos inspired by the traditional flavors of Mexican barbacoa, tender slow-cooked mutton.",
    isVeg: false,
    spicyLevel: 2,
    isTrending: true,
    isTodayDeal: false,
    tag: "Chef Special"
  },
  {
    id: "tf_5",
    name: "Chicken Lollipop",
    category: "Starters",
    price: 169,
    originalPrice: 199,
    discount: "15% OFF",
    rating: 4.9,
    ratingCount: 205,
    image: "images/chicken_lollipop.jpg",
    description: "Mix together red chilli paste, ginger garlic paste, soy sauce, chilli vinegar, and salt. Tossed crisp drummettes.",
    isVeg: false,
    spicyLevel: 2,
    isTrending: true,
    isTodayDeal: true,
    tag: "🔥 Hot & Spicy"
  },
  {
    id: "tf_6",
    name: "Chicken Chilli Dry",
    category: "Starters",
    price: 179,
    originalPrice: 209,
    discount: "15% OFF",
    rating: 4.8,
    ratingCount: 190,
    image: "images/sizzling_starter.png",
    description: "Consisting of tender fried chicken bites tossed in a super aromatic sweet, spicy and slightly tangy sauce.",
    isVeg: false,
    spicyLevel: 3,
    isTrending: true,
    isTodayDeal: false,
    tag: "Must Try"
  },
  {
    id: "tf_7",
    name: "Chicken Hot Garlic Dry",
    category: "Starters",
    price: 179,
    originalPrice: 209,
    discount: "15% OFF",
    rating: 4.8,
    ratingCount: 130,
    image: "images/sizzling_starter.png",
    description: "Boneless chicken, soy sauce, capsicum, red chilli sauce, spring onions, vinegar and lots of garlic.",
    isVeg: false,
    spicyLevel: 3,
    isTrending: false,
    isTodayDeal: false,
    tag: "Garlic Special"
  },
  {
    id: "tf_8",
    name: "Paneer Chilli Dry",
    category: "Starters",
    price: 169,
    originalPrice: 199,
    discount: "15% OFF",
    rating: 4.8,
    ratingCount: 140,
    image: "images/paneer_tikka.jpg",
    description: "Crispy paneer cubes sautéed with cornflour, black pepper, bell peppers, spring onion and soy glaze.",
    isVeg: true,
    spicyLevel: 2,
    isTrending: true,
    isTodayDeal: false,
    tag: "Veg Bestseller"
  },
  {
    id: "tf_9",
    name: "Honey Chilli Pineapple",
    category: "Starters",
    price: 139,
    originalPrice: 169,
    discount: "18% OFF",
    rating: 4.7,
    ratingCount: 75,
    image: "images/hero_taco.png",
    description: "Juicy pineapple cut into 1-inch cubes marinated in honey, lemon juice, chilli flakes & oregano.",
    isVeg: true,
    spicyLevel: 1,
    isTrending: false,
    isTodayDeal: true,
    tag: "Sweet & Spicy"
  },
  {
    id: "tf_10",
    name: "Tandoori Paneer Tikka",
    category: "Starters",
    price: 169,
    originalPrice: 199,
    discount: "15% OFF",
    rating: 4.9,
    ratingCount: 185,
    image: "images/paneer_tikka.jpg",
    description: "North Indian appetizer where chunks of paneer are marinated in spiced yogurt and grilled in a Tandoor.",
    isVeg: true,
    spicyLevel: 2,
    isTrending: true,
    isTodayDeal: true,
    tag: "Tandoori Special"
  },
  {
    id: "tf_11",
    name: "Chicken Kathi Roll",
    category: "Starters",
    price: 139,
    originalPrice: 169,
    discount: "18% OFF",
    rating: 4.9,
    ratingCount: 220,
    image: "images/kathi_roll.jpg",
    description: "Juicy chicken marinated in creamy yogurt and spices, rolled up in a buttery, flaky paratha with green chutney.",
    isVeg: false,
    spicyLevel: 2,
    isTrending: true,
    isTodayDeal: false,
    tag: "Kolkata Special"
  },
  {
    id: "tf_12",
    name: "Egg Kathi Roll",
    category: "Starters",
    price: 89,
    originalPrice: 109,
    discount: "18% OFF",
    rating: 4.8,
    ratingCount: 165,
    image: "images/egg_kathi_roll.jpg",
    description: "Kolkata Egg Rolls with golden fried egg layer, crunchy veggies, green chilies, chat masala, drizzle of ketchup wrapped in a flaky warm paratha.",
    isVeg: false,
    spicyLevel: 1,
    isTrending: false,
    isTodayDeal: false,
    tag: "Street Favorite"
  },
  {
    id: "tf_13",
    name: "Chicken 65",
    category: "Starters",
    price: 159,
    originalPrice: 189,
    discount: "16% OFF",
    rating: 4.9,
    ratingCount: 175,
    image: "images/sizzling_starter.png",
    description: "Chicken 65 is a spicy, deep-fried starter snack marinated in yogurt, spices, curry leaves and green chillies.",
    isVeg: false,
    spicyLevel: 3,
    isTrending: true,
    isTodayDeal: false,
    tag: "Spicy Crunch"
  },
  {
    id: "tf_14",
    name: "Fish Amritsari Fry",
    category: "Starters",
    price: 149,
    originalPrice: 179,
    discount: "17% OFF",
    rating: 4.8,
    ratingCount: 95,
    image: "images/fish_amritsari_fry.jpg",
    description: "Lightly battered fish fry seasoned with Indian spices, ginger garlic paste, carom seeds and gram flour.",
    isVeg: false,
    spicyLevel: 2,
    isTrending: false,
    isTodayDeal: false,
    tag: "Amritsari Special"
  },
  {
    id: "tf_15",
    name: "Fish Salt and Pepper",
    category: "Starters",
    price: 149,
    originalPrice: 179,
    discount: "17% OFF",
    rating: 4.7,
    ratingCount: 82,
    image: "images/fish_amritsari_fry.jpg",
    description: "Crispy golden fried fish tossed with garlic, chillies, spring onions, peppers, and flavourful seasonings.",
    isVeg: false,
    spicyLevel: 2,
    isTrending: false,
    isTodayDeal: false,
    tag: "Salt & Pepper"
  },
  {
    id: "tf_16",
    name: "Fish Chilli Dry",
    category: "Starters",
    price: 149,
    originalPrice: 179,
    discount: "17% OFF",
    rating: 4.8,
    ratingCount: 105,
    image: "images/katla_fish_kalia.jpg",
    description: "Heat oil in a pan, add garlic, onions, capsicum, chillies and sauté for 2 mins. Add in fish and green chilli.",
    isVeg: false,
    spicyLevel: 3,
    isTrending: false,
    isTodayDeal: false,
    tag: "Fiery Fish"
  },
  {
    id: "tf_17",
    name: "Honey Chilli Wings",
    category: "Starters",
    price: 149,
    originalPrice: 179,
    discount: "17% OFF",
    rating: 4.9,
    ratingCount: 140,
    image: "images/chicken_lollipop.jpg",
    description: "Smoked chicken wings fried to crispy perfection, tossed in a sweet and spicy chili oil glaze.",
    isVeg: false,
    spicyLevel: 2,
    isTrending: true,
    isTodayDeal: false,
    tag: "Wing Special"
  },
  {
    id: "tf_18",
    name: "Omelette",
    category: "Starters",
    price: 19,
    originalPrice: 25,
    discount: "24% OFF",
    rating: 4.6,
    ratingCount: 90,
    image: "images/egg_kathi_roll.jpg",
    description: "2 large eggs, teaspoons water, salt, freshly ground black pepper, unsalted butter seasoned on pan.",
    isVeg: false,
    spicyLevel: 1,
    isTrending: false,
    isTodayDeal: false,
    tag: "Quick Snack"
  },

  // --- SOUPS & SALADS ---
  {
    id: "tf_19",
    name: "Veg Manchow Soup",
    category: "Soups & Salads",
    price: 99,
    originalPrice: 119,
    discount: "17% OFF",
    rating: 4.7,
    ratingCount: 115,
    image: "images/hero_chinese.png",
    description: "Hot and spicy veg Indo-Chinese soup served piping hot topped with crispy fried noodles.",
    isVeg: true,
    spicyLevel: 2,
    isTrending: false,
    isTodayDeal: false,
    tag: "Classic Soup"
  },
  {
    id: "tf_20",
    name: "Veg Sweet Corn Soup",
    category: "Soups & Salads",
    price: 129,
    originalPrice: 149,
    discount: "13% OFF",
    rating: 4.8,
    ratingCount: 98,
    image: "images/hero_chinese.png",
    description: "Indo Chinese style soup made with mixed veggies, sweet corn kernels & crushed black pepper.",
    isVeg: true,
    spicyLevel: 0,
    isTrending: false,
    isTodayDeal: false,
    tag: "Comfort Bowl"
  },
  {
    id: "tf_21",
    name: "Chicken Hot and Sour Soup",
    category: "Soups & Salads",
    price: 169,
    originalPrice: 199,
    discount: "15% OFF",
    rating: 4.9,
    ratingCount: 155,
    image: "images/hero_chinese.png",
    description: "Combine the chicken broth, water, mushrooms, bamboo shoots, ginger, garlic, soy sauce, and hot pepper flakes.",
    isVeg: false,
    spicyLevel: 2,
    isTrending: true,
    isTodayDeal: false,
    tag: "Hot & Sour"
  },
  {
    id: "tf_22",
    name: "Chicken Sweet Corn Soup",
    category: "Soups & Salads",
    price: 169,
    originalPrice: 199,
    discount: "15% OFF",
    rating: 4.8,
    ratingCount: 125,
    image: "images/hero_chinese.png",
    description: "Made with a flavour packed chicken stock and has sweet kernels, satin thin egg ribbons and shredded chicken.",
    isVeg: false,
    spicyLevel: 0,
    isTrending: false,
    isTodayDeal: false,
    tag: "Rich Chicken"
  },
  {
    id: "tf_23",
    name: "Green Salad",
    category: "Soups & Salads",
    price: 39,
    originalPrice: 49,
    discount: "20% OFF",
    rating: 4.6,
    ratingCount: 65,
    image: "images/green_salad.jpg",
    description: "Made with fresh leafy greens, a delicious dressing featuring extra-virgin olive oil and balsamic vinegar.",
    isVeg: true,
    spicyLevel: 0,
    isTrending: false,
    isTodayDeal: false,
    tag: "Healthy Fit"
  },
  {
    id: "tf_24",
    name: "Chicken Salad",
    category: "Soups & Salads",
    price: 69,
    originalPrice: 89,
    discount: "22% OFF",
    rating: 4.7,
    ratingCount: 88,
    image: "images/chicken_salad.jpg",
    description: "Creamy mayonnaise binds together all ingredients for chicken salad into a satisfying mixture of flavors.",
    isVeg: false,
    spicyLevel: 0,
    isTrending: false,
    isTodayDeal: false,
    tag: "Creamy Salad"
  },
  {
    id: "tf_25",
    name: "Fruit Salad",
    category: "Soups & Salads",
    price: 79,
    originalPrice: 99,
    discount: "20% OFF",
    rating: 4.9,
    ratingCount: 140,
    image: "images/fruit_salad.jpg",
    description: "Combines fresh pineapple, oranges, grapes in a sweet citrusy syrup for a colorful dessert.",
    isVeg: true,
    spicyLevel: 0,
    isTrending: true,
    isTodayDeal: false,
    tag: "Fresh Fruit"
  },

  // --- RICE & BIRYANI ---
  {
    id: "tf_26",
    name: "Veg Fried Rice",
    category: "Rice & Biryani",
    price: 99,
    originalPrice: 120,
    discount: "17% OFF",
    rating: 4.7,
    ratingCount: 130,
    image: "images/fried_rice.jpg",
    description: "Made with a hearty mix of fresh vegetables, green onions, seasonings and wok-tossed spices.",
    isVeg: true,
    spicyLevel: 1,
    isTrending: false,
    isTodayDeal: false,
    tag: "Wok Special"
  },
  {
    id: "tf_27",
    name: "Egg Fried Rice",
    category: "Rice & Biryani",
    price: 119,
    originalPrice: 140,
    discount: "15% OFF",
    rating: 4.8,
    ratingCount: 155,
    image: "images/egg_fried_rice.jpg",
    description: "Scrambled eggs stir-fried with fluffy rice, spring onions, light soy sauce and seasonings.",
    isVeg: false,
    spicyLevel: 1,
    isTrending: false,
    isTodayDeal: false,
    tag: "Egg Special"
  },
  {
    id: "tf_28",
    name: "Chicken Fried Rice",
    category: "Rice & Biryani",
    price: 149,
    originalPrice: 179,
    discount: "17% OFF",
    rating: 4.9,
    ratingCount: 230,
    image: "images/chicken_fried_rice.jpg",
    description: "Cooked chicken cubes, fluffy basmati rice, soy sauce, and shredded egg stir-fried together.",
    isVeg: false,
    spicyLevel: 1,
    isTrending: true,
    isTodayDeal: true,
    tag: "Popular Wok"
  },
  {
    id: "tf_29",
    name: "Chicken Dum Biryani",
    category: "Rice & Biryani",
    price: 149,
    originalPrice: 189,
    discount: "21% OFF",
    rating: 5.0,
    ratingCount: 340,
    image: "images/chicken_dum_biryani.jpg",
    description: "Authentic slow-cooked chicken dum biryani featuring a prominent roasted chicken leg piece (drumstick), saffron basmati rice, boiled egg, aloo, mint, and fried onions.",
    isVeg: false,
    spicyLevel: 2,
    isTrending: true,
    isTodayDeal: true,
    tag: "👑 Royal Biryani"
  },
  {
    id: "tf_30",
    name: "Mutton Dum Biryani",
    category: "Rice & Biryani",
    price: 179,
    originalPrice: 219,
    discount: "18% OFF",
    rating: 4.9,
    ratingCount: 280,
    image: "images/mutton_dum_biryani.jpg",
    description: "Rich dum-cooked long grain basmati rice layered with juicy mutton bone-in pieces, boiled egg, aloo, and desi ghee.",
    isVeg: false,
    spicyLevel: 2,
    isTrending: true,
    isTodayDeal: false,
    tag: "Mutton Feast"
  },
  {
    id: "tf_31",
    name: "Bamboo Mutton Biryani",
    category: "Rice & Biryani",
    price: 219,
    originalPrice: 259,
    discount: "15% OFF",
    rating: 5.0,
    ratingCount: 195,
    image: "images/bamboo_mutton_biryani.jpg",
    description: "Mutton biryani with tender mutton pieces, boiled egg, and aloo served inside an authentic hollow bamboo stalk tube.",
    isVeg: false,
    spicyLevel: 2,
    isTrending: true,
    isTodayDeal: false,
    tag: "Bamboo Smoked"
  },
  {
    id: "tf_32",
    name: "Bamboo Chicken Biryani",
    category: "Rice & Biryani",
    price: 179,
    originalPrice: 210,
    discount: "15% OFF",
    rating: 4.9,
    ratingCount: 210,
    image: "images/bamboo_chicken_biryani.jpg",
    description: "Succulent chicken biryani with chicken leg drumstick, boiled egg, and aloo steamed inside fresh bamboo stalks.",
    isVeg: false,
    spicyLevel: 2,
    isTrending: true,
    isTodayDeal: false,
    tag: "Bamboo Special"
  },
  {
    id: "tf_33",
    name: "Jeera Rice",
    category: "Rice & Biryani",
    price: 99,
    originalPrice: 119,
    discount: "17% OFF",
    rating: 4.7,
    ratingCount: 85,
    image: "images/jeera_rice.jpg",
    description: "Fragrant long-grain basmati rice tempered with golden roasted cumin seeds and butter.",
    isVeg: true,
    spicyLevel: 0,
    isTrending: false,
    isTodayDeal: false,
    tag: "Aromatic"
  },
  {
    id: "tf_34",
    name: "Steam Rice",
    category: "Rice & Biryani",
    price: 49,
    originalPrice: 60,
    discount: "18% OFF",
    rating: 4.6,
    ratingCount: 70,
    image: "images/jeera_rice.jpg",
    description: "Fluffy steamed white long-grain basmati rice.",
    isVeg: true,
    spicyLevel: 0,
    isTrending: false,
    isTodayDeal: false,
    tag: "Side Rice"
  },
  {
    id: "tf_35",
    name: "Chicken Schezwan Fried Rice & Noodles",
    category: "Rice & Biryani",
    price: 219,
    originalPrice: 259,
    discount: "15% OFF",
    rating: 4.9,
    ratingCount: 240,
    image: "images/schezwan_chicken_fried_rice.jpg",
    description: "Spicy combination wok platter of chicken schezwan fried rice and hakka noodles.",
    isVeg: false,
    spicyLevel: 3,
    isTrending: true,
    isTodayDeal: true,
    tag: "Combo Wok"
  },
  {
    id: "tf_36",
    name: "Schezwan Egg Fried Rice",
    category: "Rice & Biryani",
    price: 119,
    originalPrice: 139,
    discount: "14% OFF",
    rating: 4.7,
    ratingCount: 110,
    image: "images/schezwan_egg_fried_rice.jpg",
    description: "Wok fried egg rice tossed in fiery home-style Schezwan chilli sauce showing scrambled egg ribbons and spring onions.",
    isVeg: false,
    spicyLevel: 2,
    isTrending: false,
    isTodayDeal: false,
    tag: "Spicy Egg"
  },
  {
    id: "tf_37",
    name: "Schezwan Chicken Fried Rice",
    category: "Rice & Biryani",
    price: 159,
    originalPrice: 189,
    discount: "16% OFF",
    rating: 4.8,
    ratingCount: 165,
    image: "images/schezwan_chicken_fried_rice.jpg",
    description: "Tender chicken cubes & aromatic rice tossed in spicy red Schezwan pepper sauce.",
    isVeg: false,
    spicyLevel: 3,
    isTrending: false,
    isTodayDeal: false,
    tag: "Fiery Rice"
  },
  {
    id: "tf_38",
    name: "Schezwan Veg Fried Rice",
    category: "Rice & Biryani",
    price: 110,
    originalPrice: 130,
    discount: "15% OFF",
    rating: 4.7,
    ratingCount: 95,
    image: "images/schezwan_veg_fried_rice.jpg",
    description: "Garden fresh vegetables and fluffy rice tossed in signature spicy Schezwan sauce.",
    isVeg: true,
    spicyLevel: 2,
    isTrending: false,
    isTodayDeal: false,
    tag: "Veg Schezwan"
  },

  // --- GRAVY & MAIN COURSE ---
  {
    id: "tf_39",
    name: "Chicken Masala",
    category: "Gravy & Main Course",
    price: 139,
    originalPrice: 169,
    discount: "18% OFF",
    rating: 4.8,
    ratingCount: 195,
    image: "images/chicken_handi.jpg",
    description: "Chicken, onion, tomato, and basic spices. Chicken marinated and cooked in spicy onion-tomato gravy.",
    isVeg: false,
    spicyLevel: 2,
    isTrending: true,
    isTodayDeal: false,
    tag: "Desi Gravy"
  },
  {
    id: "tf_40",
    name: "Chicken Do Pyaza",
    category: "Gravy & Main Course",
    price: 149,
    originalPrice: 179,
    discount: "17% OFF",
    rating: 4.8,
    ratingCount: 140,
    image: "images/chicken_handi.jpg",
    description: "Delightful one-pot chicken curry bursting with flavor of double onions, Indian spices & yogurt.",
    isVeg: false,
    spicyLevel: 2,
    isTrending: false,
    isTodayDeal: false,
    tag: "Onion Special"
  },
  {
    id: "tf_41",
    name: "Chicken Kadai",
    category: "Gravy & Main Course",
    price: 149,
    originalPrice: 179,
    discount: "17% OFF",
    rating: 4.8,
    ratingCount: 160,
    image: "images/chicken_handi.jpg",
    description: "Crunchy onions, peppers, tomatoes, ginger, and toasted spices in an authentic fragrant spicy curry.",
    isVeg: false,
    spicyLevel: 2,
    isTrending: false,
    isTodayDeal: false,
    tag: "Kadai Special"
  },
  {
    id: "tf_42",
    name: "Butter Chicken",
    category: "Gravy & Main Course",
    price: 149,
    originalPrice: 189,
    discount: "21% OFF",
    rating: 5.0,
    ratingCount: 410,
    image: "images/butter_chicken.jpg",
    description: "Creamy butter chicken combines fragrant spices with simple ingredients like butter & tomato sauce.",
    isVeg: false,
    spicyLevel: 1,
    isTrending: true,
    isTodayDeal: true,
    tag: "⭐ All-Time Favorite"
  },
  {
    id: "tf_43",
    name: "Katla Fish Kalia",
    category: "Gravy & Main Course",
    price: 149,
    originalPrice: 179,
    discount: "17% OFF",
    rating: 4.9,
    ratingCount: 180,
    image: "images/katla_fish_kalia.jpg",
    description: "Coveted Bengali fish delicacy of thick, fatty cuts of mature Katla carp in red onion ginger gravy.",
    isVeg: false,
    spicyLevel: 2,
    isTrending: true,
    isTodayDeal: false,
    tag: "Bengali Delight"
  },
  {
    id: "tf_44",
    name: "Katla Fish Fry",
    category: "Gravy & Main Course",
    price: 59,
    originalPrice: 75,
    discount: "21% OFF",
    rating: 4.8,
    ratingCount: 135,
    image: "images/fish_amritsari_fry.jpg",
    description: "Popular Indian dish featuring marinated Katla fish cutlet, coated in spices, deep-fried crispy.",
    isVeg: false,
    spicyLevel: 2,
    isTrending: false,
    isTodayDeal: false,
    tag: "Fish Fry"
  },
  {
    id: "tf_45",
    name: "Fish Do Pyaza",
    category: "Gravy & Main Course",
    price: 149,
    originalPrice: 179,
    discount: "17% OFF",
    rating: 4.7,
    ratingCount: 95,
    image: "images/katla_fish_kalia.jpg",
    description: "Fish cooked in spicy and flavorful Indian masala with caramelized onions and warm spices.",
    isVeg: false,
    spicyLevel: 2,
    isTrending: false,
    isTodayDeal: false,
    tag: "Fish Curry"
  },
  {
    id: "tf_46",
    name: "Chicken Tikka Masala",
    category: "Gravy & Main Course",
    price: 219,
    originalPrice: 259,
    discount: "15% OFF",
    rating: 5.0,
    ratingCount: 290,
    image: "images/chicken_handi.jpg",
    description: "Popular curried dish made with boneless chicken tikka, ground spices, onions, tomatoes and cream.",
    isVeg: false,
    spicyLevel: 2,
    isTrending: true,
    isTodayDeal: true,
    tag: "Tikka Special"
  },
  {
    id: "tf_47",
    name: "Chicken Keema Masala",
    category: "Gravy & Main Course",
    price: 149,
    originalPrice: 179,
    discount: "17% OFF",
    rating: 4.8,
    ratingCount: 150,
    image: "images/tawa_roti_chicken_keema.jpg",
    description: "Ground chicken, herbs & aromatic spices in a savory onion-tomato gravy.",
    isVeg: false,
    spicyLevel: 2,
    isTrending: false,
    isTodayDeal: false,
    tag: "Keema Curry"
  },
  {
    id: "tf_48",
    name: "Chicken Handi",
    category: "Gravy & Main Course",
    price: 229,
    originalPrice: 269,
    discount: "15% OFF",
    rating: 4.9,
    ratingCount: 210,
    image: "images/chicken_handi.jpg",
    description: "Authentic chicken curry preparation in earthen clay Handi with juicy chicken leg pieces, mustard oil, and herbs.",
    isVeg: false,
    spicyLevel: 2,
    isTrending: true,
    isTodayDeal: false,
    tag: "Handi Special"
  },
  {
    id: "tf_49",
    name: "Mutton Masala",
    category: "Gravy & Main Course",
    price: 239,
    originalPrice: 279,
    discount: "14% OFF",
    rating: 4.9,
    ratingCount: 225,
    image: "images/mutton_handi.jpg",
    description: "One pot dish where succulent mutton chunks are marinated and cooked with spices, herbs, onions, tomatoes and yogurt.",
    isVeg: false,
    spicyLevel: 2,
    isTrending: true,
    isTodayDeal: false,
    tag: "Mutton Special"
  },
  {
    id: "tf_50",
    name: "Mutton Handi",
    category: "Gravy & Main Course",
    price: 349,
    originalPrice: 399,
    discount: "13% OFF",
    rating: 5.0,
    ratingCount: 310,
    image: "images/mutton_handi.jpg",
    description: "Turmeric, red chilli powder, coriander and garam masala mutton curry with visible tender mutton bone-in pieces cooked slow in earthen pot.",
    isVeg: false,
    spicyLevel: 3,
    isTrending: true,
    isTodayDeal: true,
    tag: "Grand Mutton"
  },
  {
    id: "tf_51",
    name: "Tawa Mutton",
    category: "Gravy & Main Course",
    price: 299,
    originalPrice: 349,
    discount: "14% OFF",
    rating: 4.8,
    ratingCount: 170,
    image: "images/mutton_handi.jpg",
    description: "Delicious mutton recipe with tender goat meat pressure-cooked with curd, ginger garlic and roasted spice.",
    isVeg: false,
    spicyLevel: 2,
    isTrending: false,
    isTodayDeal: false,
    tag: "Tawa Special"
  },

  // --- COMBOS & ROTIS ---
  {
    id: "tf_52",
    name: "Egg Fried Rice with Chicken Chilli Combo",
    category: "Combos & Rotis",
    price: 179,
    originalPrice: 219,
    discount: "18% OFF",
    rating: 4.9,
    ratingCount: 260,
    image: "images/egg_fried_rice_chicken.jpg",
    description: "Delicious combination meal of egg fried rice with visible scrambled egg ribbons served with hot chicken chilli gravy.",
    isVeg: false,
    spicyLevel: 2,
    isTrending: true,
    isTodayDeal: true,
    tag: "Lovely Combo"
  },
  {
    id: "tf_53",
    name: "Aloo Paratha with Chicken Masala Combo",
    category: "Combos & Rotis",
    price: 105,
    originalPrice: 135,
    discount: "22% OFF",
    rating: 4.9,
    ratingCount: 190,
    image: "images/aloo_paratha.jpg",
    description: "Soft stuffed aloo paratha paired with flavorful chicken masala gravy combo.",
    isVeg: false,
    spicyLevel: 2,
    isTrending: true,
    isTodayDeal: true,
    tag: "Value Combo"
  },
  {
    id: "tf_54",
    name: "Tawa Roti with Chicken Keema Masala Combo",
    category: "Combos & Rotis",
    price: 149,
    originalPrice: 179,
    discount: "17% OFF",
    rating: 4.8,
    ratingCount: 145,
    image: "images/tawa_roti_chicken_keema.jpg",
    description: "Fresh hot tawa rotis served with spicy minced chicken keema masala curry.",
    isVeg: false,
    spicyLevel: 2,
    isTrending: true,
    isTodayDeal: false,
    tag: "Keema Combo"
  },
  {
    id: "tf_55",
    name: "Special Thali Combo (Steam Rice/Fish Fry/Chicken Masala/Sweets)",
    category: "Combos & Rotis",
    price: 149,
    originalPrice: 199,
    discount: "25% OFF",
    rating: 5.0,
    ratingCount: 380,
    image: "images/thali_combo.jpg",
    description: "Grand thali meal with steam rice, crispy fish fry, chicken masala, roti and sweets.",
    isVeg: false,
    spicyLevel: 2,
    isTrending: true,
    isTodayDeal: true,
    tag: "👑 Grand Thali"
  },
  {
    id: "tf_56",
    name: "Tawa Roti",
    category: "Combos & Rotis",
    price: 9,
    originalPrice: 12,
    discount: "25% OFF",
    rating: 4.7,
    ratingCount: 500,
    image: "images/tawa_roti_chicken_keema.jpg",
    description: "Freshly baked whole wheat flatbread on traditional tawa.",
    isVeg: true,
    spicyLevel: 0,
    isTrending: false,
    isTodayDeal: false,
    tag: "Fresh Roti"
  },
  {
    id: "tf_57",
    name: "Tawa Roti with Butter",
    category: "Combos & Rotis",
    price: 15,
    originalPrice: 18,
    discount: "17% OFF",
    rating: 4.8,
    ratingCount: 420,
    image: "images/tawa_roti_chicken_keema.jpg",
    description: "Warm tawa roti brushed with golden melted butter.",
    isVeg: true,
    spicyLevel: 0,
    isTrending: false,
    isTodayDeal: false,
    tag: "Butter Roti"
  },
  {
    id: "tf_58",
    name: "Tawa Roti with Ghee",
    category: "Combos & Rotis",
    price: 15,
    originalPrice: 18,
    discount: "17% OFF",
    rating: 4.8,
    ratingCount: 310,
    image: "images/tawa_roti_chicken_keema.jpg",
    description: "Tawa roti brushed with pure fragrant desi ghee.",
    isVeg: true,
    spicyLevel: 0,
    isTrending: false,
    isTodayDeal: false,
    tag: "Ghee Roti"
  },
  {
    id: "tf_59",
    name: "Aloo Paratha",
    category: "Combos & Rotis",
    price: 29,
    originalPrice: 35,
    discount: "17% OFF",
    rating: 4.8,
    ratingCount: 230,
    image: "images/aloo_paratha.jpg",
    description: "Whole wheat paratha stuffed with spiced mashed potato filling.",
    isVeg: true,
    spicyLevel: 1,
    isTrending: false,
    isTodayDeal: false,
    tag: "Veg Paratha"
  },
  {
    id: "tf_60",
    name: "Chicken Keema Paratha",
    category: "Combos & Rotis",
    price: 49,
    originalPrice: 59,
    discount: "17% OFF",
    rating: 4.9,
    ratingCount: 180,
    image: "images/tawa_roti_chicken_keema.jpg",
    description: "Flaky Indian paratha filled with savory minced chicken herbs and spices.",
    isVeg: false,
    spicyLevel: 2,
    isTrending: false,
    isTodayDeal: false,
    tag: "Chicken Paratha"
  },
  {
    id: "tf_61",
    name: "Mutton Keema Paratha",
    category: "Combos & Rotis",
    price: 79,
    originalPrice: 95,
    discount: "17% OFF",
    rating: 4.9,
    ratingCount: 160,
    image: "images/mutton_keema_paratha.jpg",
    description: "Crispy paratha stuffed with rich spicy mutton keema filling.",
    isVeg: false,
    spicyLevel: 2,
    isTrending: true,
    isTodayDeal: false,
    tag: "Mutton Paratha"
  },

  // --- DRINKS & BEVERAGES ---
  {
    id: "tf_62",
    name: "Fresh Lime Soda",
    category: "Drinks & Beverages",
    price: 29,
    originalPrice: 39,
    discount: "25% OFF",
    rating: 4.8,
    ratingCount: 220,
    image: "images/masala_coca_cola.jpg",
    description: "Chilled fizzy soda with fresh lime juice, mint leaves, and sugar/salt syrup.",
    isVeg: true,
    spicyLevel: 0,
    isTrending: true,
    isTodayDeal: false,
    tag: "Cooler"
  },
  {
    id: "tf_63",
    name: "Coca Cola",
    category: "Drinks & Beverages",
    price: 29,
    originalPrice: 35,
    discount: "17% OFF",
    rating: 4.7,
    ratingCount: 180,
    image: "images/masala_coca_cola.jpg",
    description: "Classic chilled carbonated soft drink 300ml.",
    isVeg: true,
    spicyLevel: 0,
    isTrending: false,
    isTodayDeal: false,
    tag: "Cold Drink"
  },
  {
    id: "tf_64",
    name: "Sprite",
    category: "Drinks & Beverages",
    price: 29,
    originalPrice: 35,
    discount: "17% OFF",
    rating: 4.7,
    ratingCount: 150,
    image: "images/sprite.jpg",
    description: "Crisp, refreshing lemon-lime carbonated beverage 300ml.",
    isVeg: true,
    spicyLevel: 0,
    isTrending: false,
    isTodayDeal: false,
    tag: "Fizzy Soda"
  },
  {
    id: "tf_65",
    name: "Masala Coca Cola",
    category: "Drinks & Beverages",
    price: 49,
    originalPrice: 60,
    discount: "18% OFF",
    rating: 4.9,
    ratingCount: 240,
    image: "images/masala_coca_cola.jpg",
    description: "Coca cola spiced up with black salt, roasted cumin, chaat masala, and fresh lemon juice.",
    isVeg: true,
    spicyLevel: 0,
    isTrending: true,
    isTodayDeal: false,
    tag: "Spiced Coke"
  },
  {
    id: "tf_66",
    name: "Sweet Lassi",
    category: "Drinks & Beverages",
    price: 49,
    originalPrice: 60,
    discount: "18% OFF",
    rating: 4.8,
    ratingCount: 190,
    image: "images/sweet_lassi.jpg",
    description: "Traditional rich and creamy churned sweet yogurt drink topped with malai.",
    isVeg: true,
    spicyLevel: 0,
    isTrending: false,
    isTodayDeal: false,
    tag: "Desi Lassi"
  },
  {
    id: "tf_67",
    name: "Mango Lassi",
    category: "Drinks & Beverages",
    price: 49,
    originalPrice: 65,
    discount: "25% OFF",
    rating: 5.0,
    ratingCount: 310,
    image: "images/mango_lassi.jpg",
    description: "Creamy yogurt drink blended with sweet Alphonso mango pulp and cardamom.",
    isVeg: true,
    spicyLevel: 0,
    isTrending: true,
    isTodayDeal: true,
    tag: "Mango Special"
  },
  {
    id: "tf_68",
    name: "Virgin Pina Colada",
    category: "Drinks & Beverages",
    price: 49,
    originalPrice: 65,
    discount: "25% OFF",
    rating: 4.9,
    ratingCount: 175,
    image: "images/virgin_pina_colada.jpg",
    description: "Tropical mocktail with creamy coconut milk and fresh pineapple juice over crushed ice.",
    isVeg: true,
    spicyLevel: 0,
    isTrending: true,
    isTodayDeal: false,
    tag: "Mocktail"
  }
];

const PROMO_SLIDES = [
  {
    id: 1,
    dishId: "tf_29",
    title: "Royal Chicken Dum Biryani",
    subtitle: "AUTHENTIC DUM SPICE & SAFFRON RICE",
    offer: "FLAT 21% OFF @ JUST ₹149",
    code: "BIRYANI149",
    badge: "👑 Most Popular",
    image: "images/chicken_dum_biryani.jpg",
    cta: "Order Biryani Now",
    filterCategory: "Rice & Biryani"
  },
  {
    id: 2,
    dishId: "tf_2",
    title: "Signature Mexican Tacos",
    subtitle: "AUTHENTIC CHEESY TACO FEAST",
    offer: "FLAT 15% OFF",
    code: "TACO149",
    badge: "🌮 Hot & Crispy",
    image: "images/chicken_taco.jpg",
    cta: "Explore Tacos",
    filterCategory: "Starters"
  },
  {
    id: 3,
    dishId: "tf_55",
    title: "Grand Special Thali Combo",
    subtitle: "STEAM RICE + FISH FRY + CHICKEN MASALA + SWEETS",
    offer: "SPECIAL @ JUST ₹149",
    code: "THALICOMBO",
    badge: "🔥 Best Value",
    image: "images/thali_combo.jpg",
    cta: "Claim Thali Offer",
    filterCategory: "Combos & Rotis"
  }
];

const GALLERY_PHOTOS = [
  {
    id: "g1",
    title: "Main Dining Hall & Stencil Pillars",
    category: "Interior",
    image: "images/gallery_dining_hall.jpg",
    caption: "Spacious seating hall featuring teal & yellow signature stenciled pillars and ambient ceiling lights at Bhupati Nagar."
  },
  {
    id: "g2",
    title: "Grand Gourmet Food Feast",
    category: "Food",
    image: "images/gallery_food_spread.jpg",
    caption: "Delicious table spread featuring Steamed Momos with fiery chutney, Szechuan Chilli Starters, Crispy Samosas, and Fresh Fruit Salad."
  },
  {
    id: "g3",
    title: "TACO Foodies Night Exterior View",
    category: "Exterior",
    image: "images/gallery_night_exterior.jpg",
    caption: "Stunning night illumination with glowing red TACO Foodies neon logo, fairy lights, and blue staircase railings."
  },
  {
    id: "g4",
    title: "Cozy Dining Corner & Ambience",
    category: "Interior",
    image: "images/gallery_cozy_dining.jpg",
    caption: "Warm indoor seating corner with rich wooden floors, vibrant teal walls, red drapes, and restaurant branding."
  },
  {
    id: "g5",
    title: "Signature Red Neon Logo Wall",
    category: "Interior",
    image: "images/gallery_neon_wall.jpg",
    caption: "Illuminated red TACO Foodies neon fork logo wall with birthday celebration banner and custom menu table."
  },
  {
    id: "g6",
    title: "Vibrant Dining Ambiance",
    category: "Interior",
    image: "images/restaurant_interior.png",
    caption: "Modern yellow and teal floral stencil walls with sleek dining tables at Bhupati Nagar."
  },
  {
    id: "g7",
    title: "Signature Sizzler Platter",
    category: "Food",
    image: "images/sizzling_starter.png",
    caption: "Freshly tossed Indo-Chinese chili chicken served on a sizzling hot plate with raw onions & dips."
  },
  {
    id: "g8",
    title: "Flaming Taco Trio",
    category: "Food",
    image: "images/chicken_taco.jpg",
    caption: "Loaded Mexican taco feast topped with cilantro and fresh salsa."
  },
  {
    id: "g9",
    title: "Royal Dum Biryani",
    category: "Food",
    image: "images/chicken_dum_biryani.jpg",
    caption: "Authentic dum biryani cooked in traditional earthen handi."
  }
];

const CUSTOMER_REVIEWS = [
  {
    id: "r1",
    name: "Preetam Pal",
    rating: 5,
    date: "1 month ago",
    comment: "Awesome food quality and very cozy interior! The Mexican tacos and Dum Biryani are a must-try in Bhupati Nagar.",
    avatar: "PP"
  },
  {
    id: "r2",
    name: "Ankan Mandal",
    rating: 5,
    date: "2 weeks ago",
    comment: "Top-class presentation and taste! Butter Chicken & Thali combo was piping hot and super flavorful. 5 star rating well deserved!",
    avatar: "AM"
  },
  {
    id: "r3",
    name: "Ranjan Mitra",
    rating: 5,
    date: "3 weeks ago",
    comment: "Great spot for foodies! 24/7 service is super helpful. Friendly staff and awesome combo meals under ₹150.",
    avatar: "RM"
  }
];
